sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

language: node_js
node_js:
  - "6"

os:
  - linux
  - osx

addons:
  apt:
    packages:
      # Stack dependencies
      - libgmp-dev

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH="$HOME/.local/bin:$PATH"
  - |
    if [ `uname` = "Darwin" ]
    then
      travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
install:
  - stack --version
  - stack install --install-ghc --local-bin-path ~/.local/bin fast-tags hasktags ghc-mod
  - cd client
  - npm install
  - npm run vscode:prepublish
  - cd ../server
  - npm install
  - npm run compile

script:
  - npm test
  - npm run tslint
  - cd ../client
  - npm run tslint